services:
  backend:
    build: .
    container_name: todo-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-lk8vq$^%u0s8s#w2y5uz49&kldkcao=s5ynn)!5znbca7h
      - DEBUG=TRUE