version: '3'

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=todo_app
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=todo_app_db

  backend:
    build: .
    container_name: backend
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py initiate_admin &&
                    python manage.py collectstatic --noinput &&
                    gunicorn core.wsgi --bind 0.0.0.0:8000"
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env 
    depends_on:
      - redis
      - db
  
  worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env 
    depends_on:
      - redis
      - backend

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - redis
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
