name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Docker-Compose
      run: docker-compose up -d
    - name: Run Flake8
      run: docker exec backend sh -c "flake8 ."
    - name: Run Pytest
      run: docker exec backend sh -c "pytest ."
